### DataAging API - Testes de Usuários
@baseUrl = http://localhost:8000/api/v1

### 1. Criar Usuário Gestor (Credenciais da página de login)
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "profile_type": "gestor",
  "nome_completo": "Usuário de Teste",
  "cpf": "11144477735",
  "telefone": "(41) 99999-9999",
  "sexo": "M",
  "data_nascimento": "1990-01-15",
  "cep": "80010-000",
  "logradouro": "Rua das Flores",
  "numero": "123",
  "complemento": "Apto 45",
  "bairro": "Centro",
  "municipio": "Curitiba",
  "uf": "PR",
  "matricula": "TEST001",
  "password": "senha123",
  "recovery_password": "senha123"
}

### 1.1. Criar Usuário Gestor (Alternativo)
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "profile_type": "gestor",
  "nome_completo": "João Silva Gestor",
  "cpf": "12345678909",
  "telefone": "(11) 99999-9999",
  "sexo": "M",
  "data_nascimento": "1990-01-15",
  "cep": "01234-567",
  "logradouro": "Rua das Flores",
  "numero": "123",
  "complemento": "Apto 45",
  "bairro": "Centro",
  "municipio": "São Paulo",
  "uf": "SP",
  "matricula": "GEST002",
  "password": "senha123",
  "recovery_password": "senha123"
}

### 2. Criar Usuário Técnico
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "profile_type": "tecnico",
  "nome_completo": "Maria Santos Técnico",
  "cpf": "12345678909",
  "telefone": "(11) 88888-8888",
  "sexo": "F",
  "data_nascimento": "1985-05-20",
  "cep": "04567-890",
  "logradouro": "Av. Paulista",
  "numero": "456",
  "complemento": "Sala 12",
  "bairro": "Bela Vista",
  "municipio": "São Paulo",
  "uf": "SP",
  "registro_profissional": "CRF12345",
  "especialidade": "Fisioterapia",
  "unidade_lotacao_id": 1,
  "password": "senha456",
  "recovery_password": "senha456"
}

### 3. Criar Usuário com CPF Duplicado (deve falhar)
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "profile_type": "gestor",
  "nome_completo": "Outro Gestor",
  "cpf": "11144477735",
  "telefone": "(11) 77777-7777",
  "matricula": "GEST003",
  "password": "senha789",
  "recovery_password": "senha789"
}

### 4. Criar Gestor com Matrícula Duplicada (deve falhar)
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "profile_type": "gestor",
  "nome_completo": "Terceiro Gestor",
  "cpf": "00000000191",
  "telefone": "(11) 66666-6666",
  "matricula": "TEST001",
  "password": "senha000",
  "recovery_password": "senha000"
}

### 5. Listar Todos os Usuários
GET {{baseUrl}}/users/

### 6. Listar Usuários com Paginação
GET {{baseUrl}}/users/?skip=0&limit=2

### 7. Buscar Usuário por ID
GET {{baseUrl}}/users/3

### 8. Buscar Usuário Inexistente (deve falhar)
GET {{baseUrl}}/users/999

### 9. Atualizar Usuário
PUT {{baseUrl}}/users/1
Content-Type: application/json

{
  "nome_completo": "João Silva Gestor",
  "telefone": "(11) 99999-8888",
  "complemento": "Apto 46"
}

### 10. Atualizar Senha do Usuário
PUT {{baseUrl}}/users/1
Content-Type: application/json

{
  "password": "senha123"
}

### 11. Atualizar Usuário Inexistente (deve falhar)
PUT {{baseUrl}}/users/999
Content-Type: application/json

{
  "nome_completo": "Usuário Inexistente"
}

### 12. Deletar Usuário
DELETE {{baseUrl}}/users/3

### 13. Deletar Usuário Inexistente (deve falhar)
DELETE {{baseUrl}}/users/999

### 14. Login com usuário criado (Credenciais da página de login)
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=11144477735&password=senha123

### 15. Login com usuário técnico
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=12345678909&password=senha456
